//! Golden-vector byte-compatibility for the canonical codec — the
//! crate's conformance battery (claims 1 and 2 of the fuller producer
//! battery, which lives with the producer: mtk-catalogue's
//! `golden_hypernet.rs` additionally rebuilds graphs and exercises
//! substitution via the re-exported types).
//!
//! Vectors under `tests/golden/` are byte-frozen copies of the
//! authority set (generated by the X0 reference implementation,
//! `acasxu/hypernet.py`); `manifest.json` pins each vector's sha256,
//! so the two checkouts of the vectors cannot drift silently.
//!
//! Three claims per fixture:
//!  1. decode: the committed bytes parse canonically;
//!  2. re-encode: parsing then serializing reproduces the bytes
//!     exactly;
//!  3. digest: the recomputed content digest equals the manifest pin.

use maitria_hypernet::Hypernet;

fn golden(name: &str) -> Vec<u8> {
    let path = format!("{}/tests/golden/{name}.axhn", env!("CARGO_MANIFEST_DIR"));
    std::fs::read(&path).unwrap_or_else(|e| panic!("read {path}: {e}"))
}

fn manifest_digest(name: &str) -> String {
    let path = format!("{}/tests/golden/manifest.json", env!("CARGO_MANIFEST_DIR"));
    let text = std::fs::read_to_string(path).expect("manifest.json");
    // Minimal extraction: find `"<name>"` then the following
    // `"sha256": "<hex>"` (the manifest is flat; no JSON dep needed).
    let at = text
        .find(&format!("\"{name}\""))
        .expect("fixture in manifest");
    let rest = &text[at..];
    let key = "\"sha256\": \"";
    let s = rest.find(key).expect("sha256 key") + key.len();
    rest[s..s + 64].to_string()
}

fn decode_reencode_digest(name: &str) {
    let bytes = golden(name);
    let h =
        Hypernet::from_canonical_bytes(&bytes).unwrap_or_else(|e| panic!("{name}: decode: {e:?}"));
    let re = h
        .canonical_bytes()
        .unwrap_or_else(|e| panic!("{name}: re-encode: {e:?}"));
    assert_eq!(re, bytes, "{name}: re-encode is not byte-identical");
    let d = h
        .digest()
        .unwrap_or_else(|e| panic!("{name}: digest: {e:?}"));
    assert_eq!(d.to_hex(), manifest_digest(name), "{name}: digest pin");
}

#[test]
fn g1_identity() {
    decode_reencode_digest("g1_identity");
}

#[test]
fn g2_allprims() {
    decode_reencode_digest("g2_allprims");
}

#[test]
fn g3_cartpole_drift() {
    decode_reencode_digest("g3_cartpole_drift");
}

#[test]
fn g4_subst_composite() {
    decode_reencode_digest("g4_subst_composite");
}

/// Truncation refuses at the DECODER (the guaranteed decoder-branch
/// specimen: keep the decode branch and the digest branch distinct,
/// each with its own specimen).
#[test]
fn truncated_refuses() {
    let bytes = golden("g2_allprims");
    for cut in [1usize, 8, 9, bytes.len() / 2, bytes.len() - 1] {
        assert!(
            Hypernet::from_canonical_bytes(&bytes[..cut]).is_err(),
            "truncation at {cut} must refuse"
        );
    }
}

/// A non-canonical byte stream refuses even when structurally
/// plausible: flipping the magic is the cheapest witness.
#[test]
fn bad_magic_refuses() {
    let mut bytes = golden("g1_identity");
    bytes[0] ^= 0x01;
    assert!(Hypernet::from_canonical_bytes(&bytes).is_err());
}
